### ISSUE TITLE
Duplicates in dictionary.py for MS TTS

### ISSUE THREAD

**Issue by sq6emm** [sq6jnx/sr0wx.py#38]
When running 'python microsoft_translator_downloader.py' with default dictionary.py you get some duplicates info, like:

metrow_na_sekunde already exists
temperatura_odczuwalna already exists

**Comment by sq6jnx** [comment]
I've run

```
$ grep Phrase pl_microsoft/dictionary.py | sort | uniq -c | grep 2
      2     Phrase(u"metrów na sekundę"),
      2     Phrase(u"temperatura odczuwalna"),
```

so it looks like there are only two duplicates.

**Comment by sq6jnx** [comment]
Thanks, @sq6emm
